# Generated by Django 5.1.4 on 2025-11-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_remove_video_video_url_video_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='watched_percent',
            new_name='progress',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
