# Generated by Django 5.1.4 on 2025-11-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_rename_watched_percent_userprogress_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='option1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
