# Generated by Django 5.1.4 on 2025-11-10 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_quiz_option1_alter_quiz_option2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='score',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_questions/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='selected_option',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
