# Generated by Django 5.1.4 on 2025-11-10 12:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_remove_quiz_question_remove_userresponse_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
