# Generated by Django 5.1.4 on 2025-11-10 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_quiz_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_image',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='video',
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('correct_option', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.quiz')),
            ],
        ),
    ]
