# Generated by Django 5.1.4 on 2025-11-12 10:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_remove_quiz_correct_option_remove_quiz_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
