# Generated by Django 5.1.4 on 2025-11-12 16:37

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_quizattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='video',
            field=models.ForeignKey(
                default=1,  # <<-- use an existing Video id here
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quizzes',
                to='learning.video'
            ),
            preserve_default=False,
        ),
    ]
