# Generated by Django 5.2.13 on 2026-04-16 16:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_alter_userresponse_options_quizattempt_submitted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
